### ISSUE TITLE
CRITICAL: Phone number visible in URL bar at 0:24

### ISSUE THREAD

**Issue by nsde** [tdeerenberg/WA-ScheduledMessenger#2]
You should delete the video before you get spam from malicious actors. Here's the line:

https://github.com/tdeerenberg/WA-ScheduledMessenger/blob/bb54256b2c55c676f439fde30b7ec4dfffef3ca5/README.md?plain=1#L17

Have a nice day, greetings from Germany

**Comment by tdeerenberg** [comment]
Thank you, had not spotted that yet. I will make a new demo video!
